---
collections:
  - name: .cache/AnsibleRoles/cisco-3850
    type: dir
  - name: .cache/AnsibleRoles/opnsense
    type: dir
  - name: .cache/AnsibleRoles/proxmox
    type: dir
  - name: .cache/AnsibleRoles/docker
    type: dir
