[all:vars]
ansible_user=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

[pve]
pve01.mgmt.etsmtl.club ansible_host=10.0.21.51
pve02.mgmt.etsmtl.club ansible_host=10.0.21.52
pve03.mgmt.etsmtl.club ansible_host=10.0.21.53
pve04.mgmt.etsmtl.club ansible_host=10.0.21.54
pve05.mgmt.etsmtl.club ansible_host=10.0.21.55
pve06.mgmt.etsmtl.club ansible_host=10.0.21.56
pve07.mgmt.etsmtl.club ansible_host=10.0.21.57
pve08.mgmt.etsmtl.club ansible_host=10.0.21.58

[ipmi:children]
ilo
idrac

[ilo]
pve01.ipmi.etsmtl.club ansible_host=10.0.21.21
pve02.ipmi.etsmtl.club ansible_host=10.0.21.22
pve03.ipmi.etsmtl.club ansible_host=10.0.21.23
pve04.ipmi.etsmtl.club ansible_host=10.0.21.24
pve07.ipmi.etsmtl.club ansible_host=10.0.21.27

[idrac]
pve05.ipmi.etsmtl.club ansible_host=10.0.21.25
pve06.ipmi.etsmtl.club ansible_host=10.0.21.26
pve08.ipmi.etsmtl.club ansible_host=10.0.21.28

[nas]
nas01.mgmt.etsmtl.club ansible_host=10.0.21.50

[ipmi]
nasmgmt01.ipmi.etsmtl.club ansible_host=10.0.21.91

[routers]
opnsense01.mgmt.etsmtl.club ansible_host=142.137.247.141
opnsense02.mgmt.etsmtl.club ansible_host=142.137.247.142

[switches:children]
nxos
ios

[nxos]
data01.mgmt.etsmtl.club ansible_host=10.0.21.41

[ios]
axs01.mgmt.etsmtl.club ansible_host=10.0.21.31
mgmt01.mgmt.etsmtl.club ansible_host=10.0.21.32

[pnp-server]
pnp01.mgmt.etsmtl.club ansible_host=10.0.21.81


[forgejo-runners]
forgejo-runner01.mgmt.etsmtl.club ansible_host=10.0.21.71
forgejo-runner02.mgmt.etsmtl.club ansible_host=10.0.21.72
forgejo-runner03.mgmt.etsmtl.club ansible_host=10.0.21.73
