---
forgejo_api_url: "https://git.staging.etsmtl.club"

vm_default_cpu_cores: 2
vm_default_memory_mb: 4096

vm_default_net:
  bridge: "vmbr0"
  vlan: 21
  netmask: "255.255.255.0"
  gateway: "10.0.21.1"

vm_default_user: root
vm_default_password: "CHANGEME"

vm_default_disk_image_path: "local:iso/ubuntu-22.04-server-cloudimg-amd64.img"
vm_default_disk_storage: "local-lvm"
vm_default_disk_format: "qcow2"
vm_default_disk_size: "30G"

forgejo_instances:
  - id: 201
    name: forgejo-runner-staging-01
    node: pve01
    ip: "10.0.21.101"
